This notebook reproduces results from Section VII: Simplexes of the paper
"Phase locking and multistability in the topological Kuramoto model on cell complexes".

It prints relevant boundary matrices and kernel matrices, generates Figure 7 and verifies
our analytical result for the dimension of the winding number vectors.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import math

from core.complexes import (
    generate_all_B_by_definition,
    compute_kernel_sp,
    get_C_from_B,
)

from core.dynamics import (
    find_all_plus_omega_zero_solutions
)

from core.simplexes import (
    generate_simplices,
    print_B_and_C_for_simplex
)


# Let us start by printing all the B and C matrices up to dimension 5.

In [4]:
for d in range(2, 6):
    print_B_and_C_for_simplex(max_dim=d)


=== Simplices up to 2-simplex ===
S[0] (3 elements): [[1], [2], [3]]
S[1] (3 elements): [[1, 2], [1, 3], [2, 3]]
S[2] (1 elements): [[1, 2, 3]]


--- Boundary matrix  B[1]  (maps from S[1] to S[0]) ---
[[-1 -1  0]
 [ 1  0 -1]
 [ 0  1  1]]
Shape: (3, 3)

Cycle matrices for n = 0
C[0] (from B[0].T @ C[0].T = 0):
[[1. 1. 1.]]
Shape: (1, 3)

C[1] (from B[1] @ C[1] = 0):
[]
Shape: (1, 0)
--------------------------------------------------------------------------------

--- Boundary matrix  B[2]  (maps from S[2] to S[1]) ---
[[ 1]
 [-1]
 [ 1]]
Shape: (3, 1)
--------------------------------------------------------------------------------

=== Simplices up to 3-simplex ===
S[0] (4 elements): [[1], [2], [3], [4]]
S[1] (6 elements): [[1, 2], [1, 3], [1, 4], [2, 3], [2, 4], [3, 4]]
S[2] (4 elements): [[1, 2, 3], [1, 2, 4], [1, 3, 4], [2, 3, 4]]
S[3] (1 elements): [[1, 2, 3, 4]]


--- Boundary matrix  B[1]  (maps from S[1] to S[0]) ---
[[-1 -1 -1  0  0  0]
 [ 1  0  0 -1 -1  0]
 [ 0  1  0  1  0 -1]

# Now we study the dynamics.

Triangle

In [3]:
dim = 2  # triangle
S = generate_simplices(dim)
B = generate_all_B_by_definition(S)

n = 0
roots_s2_n0 = find_all_plus_omega_zero_solutions(S, n, True)

n = 1
roots_s2_n1 = find_all_plus_omega_zero_solutions(S, n, True)

n = 0,
C_n = [],
C_np1 = [[ 1.]
 [-1.]
 [ 1.]]
total of 1 different z_n_vecs considered, and 1 different z_np1_vecs.
Phase-locked solutions:
(z_plus, z_minus) = ((0,), [])
zeta_plus = [0.], zeta_minus = []
Solution z+ = (0,), z- = []: is stable.
Solution z+ = (0,), z- = []: all cos(theta) > 0.
Root 1: z+ = (0,), z- = [], zeta_plus = [0.], zeta_minus = [], Stable: True, Positive: True
Cos(theta)_minus: None 
 Eig J1:None
 Cos(theta)_plus: [1. 1. 1.]
 Eig J2:[-3.00000000e+00 -3.00000000e+00  1.11022302e-16]

n = 1,
C_n = [[1. 1. 1.]],
C_np1 = []
total of 1 different z_n_vecs considered, and 1 different z_np1_vecs.
Phase-locked solutions:
(z_plus, z_minus) = ([], (0,))
zeta_plus = [], zeta_minus = [0.]
Solution z+ = [], z- = (0,): is stable.
Solution z+ = [], z- = (0,): all cos(theta) > 0.
Root 1: z+ = [], z- = (0,), zeta_plus = [], zeta_minus = [0.], Stable: True, Positive: True
Cos(theta)_minus: [1. 1. 1.] 
 Eig J1:[-3.00000000e+00 -3.00000000e+00  1.11022302e-16]
 Cos(theta)_plus: None

Tetrahedron

In [5]:
dim = 3  # tetrahedron
S = generate_simplices(dim)
B = generate_all_B_by_definition(S)

n = 0
roots_s3_n0 = find_all_plus_omega_zero_solutions(S, n, True)

n = 1
roots_s3_n1 = find_all_plus_omega_zero_solutions(S, n, True)

n = 2
roots_s3_n2 = find_all_plus_omega_zero_solutions(S, n, True)

n = 0,
C_n = [],
C_np1 = [[ 1.  1.  0.]
 [-1.  0.  1.]
 [ 0. -1. -1.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
total of 1 different z_n_vecs considered, and 1 different z_np1_vecs.
Phase-locked solutions:
(z_plus, z_minus) = ((0, 0, 0), [])
zeta_plus = [0. 0. 0.], zeta_minus = []
Solution z+ = (0, 0, 0), z- = []: is stable.
Solution z+ = (0, 0, 0), z- = []: all cos(theta) > 0.
Root 1: z+ = (0, 0, 0), z- = [], zeta_plus = [0. 0. 0.], zeta_minus = [], Stable: True, Positive: True
Cos(theta)_minus: None 
 Eig J1:None
 Cos(theta)_plus: [1. 1. 1. 1. 1. 1.]
 Eig J2:[-4.00000000e+00 -4.00000000e+00 -4.00000000e+00 -7.77156117e-16]

n = 1,
C_n = [[1. 1. 1. 1.]],
C_np1 = [[-1.]
 [ 1.]
 [-1.]
 [ 1.]]
total of 1 different z_n_vecs considered, and 1 different z_np1_vecs.
Phase-locked solutions:
(z_plus, z_minus) = ((0,), (0,))
zeta_plus = [0.], zeta_minus = [0.]
Solution z+ = (0,), z- = (0,): is stable.
Solution z+ = (0,), z- = (0,): all cos(theta) > 0.
Root 1: z+ = (0,), z- = (0,), zeta_plus

5-cell / 4-simplex. 

In [ ]:
dim = 4  # 5-cell / 4-simplex
S = generate_simplices(dim)
B = generate_all_B_by_definition(S)

n=0
roots_s4_n0 = find_all_plus_omega_zero_solutions(S, n, True)

n = 1
roots_s4_n1 = find_all_plus_omega_zero_solutions(S, n, True)

n = 2
roots_s4_n2 = find_all_plus_omega_zero_solutions(S, n, True)

n = 3
roots_s4_n3 = find_all_plus_omega_zero_solutions(S, n, True)

5-simplex (takes a while to calculate it)

In [ ]:
dim = 5  # 5-simplex
S = generate_simplices(dim)
B = generate_all_B_by_definition(S)

n=0
roots_s5_n0 = find_all_plus_omega_zero_solutions(S, n, True)

n = 1
roots_s5_n1 = find_all_plus_omega_zero_solutions(S, n, True)

n = 2
roots_s5_n2 = find_all_plus_omega_zero_solutions(S, n, True)

n = 3
roots_s5_n3 = find_all_plus_omega_zero_solutions(S, n, True)

n = 4
roots_s5_n4 = find_all_plus_omega_zero_solutions(S, n, True)

Collect results and plot

In [ ]:
roots_s2 = [len(roots_s2_n0), len(roots_s2_n1)]
roots_s3 = [len(roots_s3_n0), len(roots_s3_n1), len(roots_s3_n2)]
roots_s4 = [len(roots_s4_n0), len(roots_s4_n1), len(roots_s4_n2), len(roots_s4_n3)]
roots_s5 = [len(roots_s5_n0), len(roots_s5_n1), len(roots_s5_n2), len(roots_s5_n3), len(roots_s5_n4)]

# Collect into dict keyed by simplex dimension
roots_by_simplex = {
    2: roots_s2,
    3: roots_s3,
    4: roots_s4,
    5: roots_s5
}

# Build matrix with None where no data 
max_n = max(len(v) for v in roots_by_simplex.values()) 
matrix = []
for n in range(max_n):  
    row = []
    for d in sorted(roots_by_simplex.keys()): 
        vals = roots_by_simplex[d]
        if n < len(vals):
            row.append(vals[n])
        else:
            row.append(None)
    matrix.append(row)

matrix = np.array(matrix, dtype=object)  # rows = n, cols = simplex dimension

# Plot
fig, ax = plt.subplots(figsize=(6,4))
for i in range(matrix.shape[0]):     # n  index
    for j in range(matrix.shape[1]): # simplex dim index
        value = matrix[i, j]
        if value is not None:
            facecolor = 'lightgrey' if (value is not None and value > 1) else 'white'
            rect = plt.Rectangle([j, i], 1, 1, facecolor=facecolor, edgecolor='black')
            ax.add_patch(rect)
        #if value is not None:
            ax.text(j+0.5, i+0.5, str(value), ha='center', va='center', fontsize=14)

# Labels
simplex_dims = sorted(roots_by_simplex.keys())
ax.set_xticks(np.arange(len(simplex_dims)) + 0.5)
ax.set_xticklabels([f"{d}-simplex" for d in simplex_dims], fontsize = 14)
ax.set_yticks(np.arange(max_n) + 0.5)
ax.set_yticklabels([f"n={n}" for n in range(max_n)], fontsize = 14)

ax.set_xlim(0, len(simplex_dims))
ax.set_ylim(0, max_n)
ax.set_title("Number of stable phase-locked states", fontsize=14)
plt.tight_layout()
plt.savefig('Fig7.pdf', bbox_inches='tight')
plt.show()

Let's check our formulas for winding number vector dimensions.

In [ ]:
def verify_winding_num_dimension(dim_lo=2, dim_hi=7):
    """
    Verify, for d-simplices with d in [dim_lo, dim_hi], that:
        dim ker(B_{n+1})  = C(d, n+2)
        dim ker(B_n^T)    = C(d, n-1)
    using C-matrices computed from boundary matrices.
    """
    

    for d in range(dim_lo, dim_hi + 1):
        S = generate_simplices(d)
        B = generate_all_B_by_definition(S)

        print(f"\n--- {d}-simplex ---")

        all_ok = True  # track if all verifications pass

        for n in range(0, d):
            B_np1 = B[n]                       # B_{n+1}
            B_n   = B[n-1] if n >= 1 else None # B_n for n>=1, else None

            if n == 0:
                Cn_dim = 0
                Cnp1 = compute_kernel_sp(B_np1)
                Cnp1_dim = Cnp1.shape[1]
            else:
                Cn, Cnp1 = get_C_from_B(B_n, B_np1)
                Cn_dim   = Cn.shape[0]
                Cnp1_dim = Cnp1.shape[1]

            # theoretical values
            ker_Bnp1_theory = math.comb(d, n + 2) if (n + 2) <= d else 0
            ker_BnT_theory  = math.comb(d, n - 1) if (n - 1) >= 0 else 0

            ok_plus  = (Cnp1_dim == ker_Bnp1_theory)
            ok_minus = (Cn_dim == ker_BnT_theory)

            if not (ok_plus and ok_minus):
                all_ok = False

        # print summary for this simplex
        if all_ok:
            print(f"Verified: all kernel dimensions match binomial formulas.")
        else:
            print(f"Mismatch detected in one or more kernel dimensions.")



In [16]:
verify_winding_num_dimension(2,10)


--- 2-simplex ---
Verified: all kernel dimensions match binomial formulas.

--- 3-simplex ---
Verified: all kernel dimensions match binomial formulas.

--- 4-simplex ---
Verified: all kernel dimensions match binomial formulas.

--- 5-simplex ---


Verified: all kernel dimensions match binomial formulas.

--- 6-simplex ---
Verified: all kernel dimensions match binomial formulas.

--- 7-simplex ---
Verified: all kernel dimensions match binomial formulas.

--- 8-simplex ---
Verified: all kernel dimensions match binomial formulas.

--- 9-simplex ---
Verified: all kernel dimensions match binomial formulas.

--- 10-simplex ---
Verified: all kernel dimensions match binomial formulas.
